// EDITE AQUI SOMENTE OS PACOTES QUE DESEJA INSTALAR NO PROJETO
const pacotes = [
    // 🔹 Base do backend
    'express',
    'dotenv',
    'cors',

    // 🔹 Banco de dados
    'pg',
    '@prisma/client@7.3.0',
    '@prisma/adapter-pg@7.3.0',

    // 🔹 Upload e manipulação de arquivos
    'multer',
    'sharp',

    // 🔹 Integrações externas
    '@supabase/supabase-js',

    // 🔹 Ferramentas de desenvolvimento
    '--save-dev prisma@7.3.0',
    '--save-dev nodemon',
];

/*
 *
 * NÃO EDITE DAQUI PARA BAIXO
 *
 */
const apagar = {
    primeiro: ['inicial.js'],
    segundo: ['support.js', 'amods.js'],
};

const criarItens = {
    '.gitignore': {
        codigo: `node_modules/
.env
dist/
build/
*.log
.DS_Store
prisma/migrations/`,
    },

    'package.json': {
        codigo: `{
  "name": "NOME_DA_PASTA"
}`,
    },

    'ReadMe.MD': {
        codigo: `# 1. Criar projeto
- npm init -y

# 2. Ajustar package.json
- Adicionar: "type": "module"
- Adicionar: "main": "server.js"
- Adicionar dentro do script: "dev": "nodemon server.js"

# 3. Instalar dependência
- npm i express dotenv pg @prisma/client @prisma/adapter-pg
- npm i -D nodemon prisma

# 4. Inicializar Prisma
- npx prisma init --datasource-provider postgresql

# 5. Configurar \`.env\`
- PORT=3000
- DATABASE_URL="postgresql://usuario:senha@localhost:porta/nome_do_banco_db"

# 6. Configurar schema.prisma
- crie suas tabelas

# 7. Gerar SQL
- npx prisma migrate dev --name init
- npx prisma generate

# 8. Semear dados no banco
- npx prisma db seed

# 9. Abrir Prisma Studio
- npx prisma studio

## Casos de erros

### Após alterar schema.prisma
- npx prisma migrate dev --name nome_da_alteracao (exemplo: adicionar_tabela_users)
- npx prisma generate

### Banco inconsistente (⚠️ APAGA TUDO)
- npx prisma migrate reset

### Apenas popular dados
- npx prisma db seed

### Dicas
|   Comando       | Apaga dados?    | Cria migrations? | Uso            |
| --------------- | ------------    | ---------------- | -------------- |
| \`migrate dev\`   | ❌ Não          | ✅ Sim          | Alterar schema |
| \`db seed\`       | ❌ Não          | ❌ Não          | Popular dados  |
| \`migrate reset\` | ✅ SIM          | ❌ Não          | DEV only       |

## Clonou repositório e não existe o banco em seu PC?
- npm i
- Siga os passos 5, 7 e 8`,
    },

    '.env': {
        codigo: `PORT=`,
    },

    'prisma.config.js': {
        codigo: `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
        seed: 'node prisma/seed.js',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});`,
    },

    prisma: {
        'schema.prisma': {
            codigo: `generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
}

model Exemplo {
    id        Int      @id @default(autoincrement())
    nome      String
    estado    Boolean  @default(true)
    preco     Decimal? @db.Decimal(10, 2)

    @@map("exemplo")
}`,
        },
        'seed.js': {
            codigo: `import pg from 'pg';
import 'dotenv/config';
import pkg from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const { PrismaClient } = pkg;
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
    console.log('🌱 Resetando tabela exemplo...');

    // Remove todos os registros
    // await prisma.exemplo.deleteMany();

    console.log('📦 Inserindo novos registros...');

    await prisma.exemplo.createMany({
        data: [
            { nome: 'Exemplo Alpha' },
            { nome: 'Exemplo Beta' },
            { nome: 'Exemplo Gamma' },
            { nome: 'Exemplo Delta' },
        ],
    });

    console.log('✅ Seed concluído!');
}

main()
    .catch((e) => {
        console.error('❌ Erro no seed:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });`,
        },
    },

    src: {
        'server.js': {
            codigo: `import express from 'express';
import 'dotenv/config';
import exemplosRoutes from './routes/exemploRoute.js';

const app = express();
const PORT = process.env.PORT || 3001;

app.use(express.json());

app.get('/', (req, res) => {
    res.send('🚀 API funcionando');
});

// Rotas
app.use('/api/exemplos', exemplosRoutes);

app.use((req, res) => {
    res.status(404).json({ error: 'Rota não encontrada' });
});

app.listen(PORT, () => {
    console.log(\`🚀 Servidor rodando em http://localhost:\${PORT}\`);
});`,
        },
        models: {
            'ExemploModel.js': {
                codigo: `import prisma from '../lib/services/prismaClient.js';

export default class ExemploModel {
    constructor({ id = null, nome, estado = true, preco = null } = {}) {
        this.id = id;
        this.nome = nome;
        this.estado = estado;
        this.preco = preco;
    }

    async criar() {
        return prisma.exemplo.create({
            data: {
                nome: this.nome,
                estado: this.estado,
                preco: this.preco,
            },
        });
    }

    async atualizar() {
        return prisma.exemplo.update({
            where: { id: this.id },
            data: { nome: this.nome, estado: this.estado, preco: this.preco },
        });
    }

    async deletar() {
        return prisma.exemplo.delete({ where: { id: this.id } });
    }

    static async buscarTodos(filtros = {}) {
        const where = {};

        if (filtros.nome) {
            where.nome = { contains: filtros.nome, mode: 'insensitive' };
        }
        if (filtros.estado !== undefined) {
            where.estado = filtros.estado === 'true';
        }
        if (filtros.preco !== undefined) {
            where.preco = parseFloat(filtros.preco);
        }

        return prisma.exemplo.findMany({ where });
    }

    static async buscarPorId(id) {
        const data = await prisma.exemplo.findUnique({ where: { id } });
        if (!data) {
            return null;
        }
        return new ExemploModel(data);
    }
}`,
            },
        },

        controllers: {
            'exemploController.js': {
                codigo: `import ExemploModel from '../models/ExemploModel.js';

export const criar = async (req, res) => {
    try {
        if (!req.body) {
            return res.status(400).json({ error: 'Corpo da requisição vazio. Envie os dados!' });
        }

        const { nome, estado, preco } = req.body;

        if (!nome){
            return res.status(400).json({ error: 'O campo "nome" é obrigatório!' });
        }
        if (preco === undefined || preco === null) {
            return res.status(400).json({ error: 'O campo "preco" é obrigatório!' });
        }

        const exemplo = new ExemploModel({ nome, estado, preco: parseFloat(preco) });
        const data = await exemplo.criar();

        return res.status(201).json({ message: 'Registro criado com sucesso!', data });
    } catch (error) {
        console.error('Erro ao criar:', error);
        return res.status(500).json({ error: 'Erro interno ao salvar o registro.' });
    }
};

export const buscarTodos = async (req, res) => {
    try {
        const registros = await ExemploModel.buscarTodos(req.query);

        if (!registros || registros.length === 0) {
            return res.status(400).json({ message: 'Nenhum registro encontrado.' });
        }

        return res.status(200).json(registros);
    } catch (error) {
        console.error('Erro ao buscar:', error);
        return res.status(500).json({ error: 'Erro ao buscar registros.' });
    }
};

export const buscarPorId = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) {
            return res.status(400).json({ error: 'O ID enviado não é um número válido.' });
        }

        const exemplo = await ExemploModel.buscarPorId(parseInt(id));

        if (!exemplo) {
            return res.status(404).json({ error: 'Registro não encontrado.' });
        }

        return res.status(200).json({ data: exemplo });
    } catch (error) {
        console.error('Erro ao buscar:', error);
        return res.status(500).json({ error: 'Erro ao buscar registro.' });
    }
};

export const atualizar = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) {
            return res.status(400).json({ error: 'ID inválido.' });
        }

        if (!req.body) {
            return res.status(400).json({ error: 'Corpo da requisição vazio. Envie os dados!' });
        }

        const exemplo = await ExemploModel.buscarPorId(parseInt(id));

        if (!exemplo) {
            return res.status(404).json({ error: 'Registro não encontrado para atualizar.' });
        }

        if (req.body.nome !== undefined) {
            exemplo.nome = req.body.nome;
        }
        if (req.body.estado !== undefined) {
            exemplo.estado = req.body.estado;
        }
        if (req.body.preco !== undefined) {
            exemplo.preco = parseFloat(req.body.preco);
        }

        const data = await exemplo.atualizar();

        return res.status(200).json({ message: \`O registro "\${data.nome}" foi atualizado com sucesso!\`, data });
    } catch (error) {
        console.error('Erro ao atualizar:', error);
        return res.status(500).json({ error: 'Erro ao atualizar registro.' });
    }
};

export const deletar = async (req, res) => {
    try {
        const { id } = req.params;

        if (isNaN(id)) {
            return res.status(400).json({ error: 'ID inválido.' });
        }

        const exemplo = await ExemploModel.buscarPorId(parseInt(id));

        if (!exemplo) {
            return res.status(404).json({ error: 'Registro não encontrado para deletar.' });
        }

        await exemplo.deletar();

        return res.status(200).json({ message: \`O registro "\${exemplo.nome}" foi deletado com sucesso!\`, deletado: exemplo });
    } catch (error) {
        console.error('Erro ao deletar:', error);
        return res.status(500).json({ error: 'Erro ao deletar registro.' });
    }
};`,
            },
        },

        routes: {
            'exemploRoute.js': {
                codigo: `import express from 'express';
import * as controller from '../controllers/exemploController.js';

const router = express.Router();

router.post('/', controller.criar);
router.get('/', controller.buscarTodos);
router.get('/:id', controller.buscarPorId);
router.put('/:id', controller.atualizar);
router.delete('/:id', controller.deletar);

export default router;`,
            },
        },
        lib: {
            services: {
                'prismaClient.js': {
                    codigo: `import pg from 'pg';
import 'dotenv/config';
import pkg from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const { PrismaClient } = pkg;

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

export default prisma;`,
                },
            },
        },
    },
};

export { pacotes, criarItens, apagar };
